print("hello world")
name = input("Enter your name: ")
print(f"Hello, {name}!")
age = input("Enter your age: ")
age = int(age)
print(f"You will be {age + 1} next year")
# print(f"i am {age + 1} next year")
